version: '3'
services:
  development-service-client:
    image: node:{{project.general.node_version}}
    volumes:
      - nodemodules:/usr/src/service/node_modules:consistent
      - ./../:/usr/src/service:consistent
    environment:
      - NODE_ENV=development
    working_dir: /usr/src/service
    command: npm run serve:development
    ports:
      - '{{project.local.port}}:{{project.local.port}}'
volumes:
  nodemodules:
    external: true
