{{={{{ }}}=}}
name: Github CI [Lint]

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [{{{project.general.node_version}}}.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: docker volume create nodemodules
      - run: docker-compose -f ./.docker/docker-compose.commands.yml run --rm install
      - run: docker-compose -f ./.docker/docker-compose.commands.yml run --rm prepare
      - run: docker-compose -f ./.docker/docker-compose.commands.yml run --rm lint
        env:
          CI: true
